services:
  # --- INGESTA: APACHE KAFKA OFICIAL (MODO KRAFT - SIN ZOOKEEPER) ---
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENERS: 'INTERNAL://:9093,EXTERNAL://:9092,CONTROLLER://:9094'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:9093,EXTERNAL://localhost:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9094'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CLUSTER_ID: '4L62IdOaS-mK7gVwVof_Ag'
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - spark-net

  # --- CÓMPUTO: APACHE SPARK MASTER OFICIAL ---
  spark-master:
    build:
      context: .
      dockerfile: spark.Dockerfile
    container_name: spark-master
    ports:
      - "8080:8080"
      - "4040:4040"
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
    volumes:
      - ./:/opt/spark/work-dir
    networks:
      - spark-net

  # --- CÓMPUTO: APACHE SPARK WORKER OFICIAL ---
  spark-worker:
    build:
      context: .
      dockerfile: spark.Dockerfile
    container_name: spark-worker
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    volumes:
      - ./:/opt/spark/work-dir
    networks:
      - spark-net

  # --- DESARROLLO: JUPYTER LAB ---
  jupyter-lab:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter-lab
    user: root
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    networks:
      - spark-net

  # --- ALMACENAMIENTO: POSTGRESQL (NUEVO) ---
  postgres:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'tfm_user'
      POSTGRES_PASSWORD: 'tfm_password'
      POSTGRES_DB: 'fraud_detection'
    volumes:
      - postgres-data:/var/lib/postgresql/data #
    networks:
      - spark-net


volumes:
  kafka-data:
    driver: local
  postgres-data:
    driver: local

networks:
  spark-net:
    driver: bridge