services:
  # --- INGESTA: APACHE KAFKA OFICIAL (MODO KRAFT - SIN ZOOKEEPER) ---
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENERS: 'INTERNAL://:9093,EXTERNAL://:9092,CONTROLLER://:9094'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:9093,EXTERNAL://localhost:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9094'
      # ESTA ES LA LÍNEA QUE SOLUCIONA TU ERROR:
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CLUSTER_ID: '4L62IdOaS-mK7gVwVof_Ag'
    networks:
      - spark-net

  # --- CÓMPUTO: APACHE SPARK MASTER OFICIAL ---
  spark-master:
    image: apache/spark:3.5.1
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
    volumes:
      - ./data:/opt/spark/work-dir/data
      - ./src:/opt/spark/work-dir/src
    networks:
      - spark-net

  # --- CÓMPUTO: APACHE SPARK WORKER OFICIAL ---
  spark-worker:
    image: apache/spark:3.5.1
    container_name: spark-worker
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    volumes:
      - ./data:/opt/spark/work-dir/data
      - ./src:/opt/spark/work-dir/src
    networks:
      - spark-net

  # --- DESARROLLO: JUPYTER LAB ---
  jupyter-lab:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter-lab
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./jupyter:/home/jovyan/work
      - ./data:/home/jovyan/work/data
      - ./src:/home/jovyan/work/src
    environment:
      - JUPYTER_ENABLE_LAB=yes
    networks:
      - spark-net

networks:
  spark-net:
    driver: bridge